### ISSUE TITLE
Density compensation

### ISSUE THREAD

**Issue by aTrotier** [andyschwarzl/gpuNUFFT#59]
Hi,
First, i want to thank you for your work.

I try to use the last commit  (Jul 2, 2017) and it seems you have changed the way you used the density compensation.

I'm currently using the mex function SDC3 from (http://www.ismrm.org/mri_unbound/sequence.htm) in order to generate density compensation vector. In release, 2.0.8 i have to directly passed the result "w" and now, i have to pass "w.^2". 

Is that normal ?

While i'm here, how do you generate the density compensation vector ? Are you using gpuNUFFT, passing a vector of one ?

**Comment by andyschwarzl** [comment]
Hi,

yes, there has been a major change in the application of the density compensation, see 844342b4.
The density compensation is now applied with sqrt(w) both in the forward and adjoint operation. The reason is to support intrinsic adjointness for iterative solvers.

For single reconstructions the data has to be scaled with sqrt(w) or as you correctly mentioned pass w.^2.

HTH

**Comment by andyschwarzl** [comment]
Currently, the gpuNUFFT is not estimating the density compensation vector. Passing a unit vector to the forward operation would be a correct approach.

**Comment by aTrotier** [comment]
Thanks for your response.
