### ISSUE TITLE
Missing NUFFT function

### ISSUE THREAD

**Issue by janden** [andyschwarzl/gpuNUFFT#62]
In `gradient_demo.m`, a function `NUFFT` is called, but it does not seem to be in the package. At the beginning of the script, an `addpath` command is issued for `../../../fessler/NUFFT`. However, it is not clear what this toolbox refers to. The function call does not seem to match that of the `nufft` function in the IRT toolbox.

**Comment by FlorianKnoll** [comment]
Hi Joakim,

thanks for spotting this. The missing function is a class-interface NUFFT to Jeff Fessler's nufft toolbox that follows the same structure as the @gpuNUFFT interface to our library. We haven't included it since it is not part of the core package, but you can get something similar from Miki Lustig's sparseMRI reconstruction package that will work with our code.

http://people.eecs.berkeley.edu/~mlustig/software/sparseMRI_v0.2.tar.gz

Best wishes, Florian

**Comment by janden** [comment]
That works great. Thank you!

**Comment by FlorianKnoll** [comment]
As a follow up comment, a version of this class interface for 3D trajectories is now included here, and the demos have been updated.

**Comment by janden** [comment]
Thank you. This will make things a lot easier.
